services:
  server:
    depends_on:
      - db
      - ollama
    build:
      context: .
    ports:
      - 3000:3000
    env_file:
      - .env

  db:
    image: mongo:latest
    container_name: ollamachat_mongo
    restart: always
    ports:
      - '27018:27017'
    volumes:
      - docker_chatx_data:/data/db

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - '11434:11434'
    volumes:
      - /home/fadil/.ollama:/root/.ollama
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
    restart: unless-stopped

volumes:
  docker_chatx_data:
  ollama_data:
