import Navbar from '@/components/shared/navbar'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <body className='bg-[#212121] '>
        <Navbar />
        <main> {children}</main>
      </body>
    </html>
  )
}
